services:
  maven:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/docker/maven}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        BASE_IMAGE_TAG:
        DIRPATH:
        MAVEN_OPTS:
