version: '3.5'

services:
  maven:
    image: ${IMAGE_NAME:-registry.gitlab.com/redmic-project/docker/maven}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        MAVEN_IMAGE_TAG:
        GDAL_BIN_VERSION:
        LIBXML2_UTILS_VERSION:
        DOCKER_VERSION:
        DIRPATH:
        MAVEN_OPTS:
